services:
  backend:
    build: ./apps/backend
    ports:
      - "1337:1337"
    env_file:
      - ./apps/backend/.env
  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
